# Generated by Django 4.0.3 on 2022-10-08 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='Наличие, 1, если есть'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.FileField(blank=True, default='nofoto.jpeg', null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.CharField(max_length=255, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='added_by_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppOko.staffuser'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppOko.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_discount_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_max_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppOko.subcategories'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppOko.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='1, если активно'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=models.FileField(blank=True, default='nofoto.jpeg', null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='url_slug',
            field=models.CharField(max_length=255, verbose_name='URL-название'),
        ),
    ]
