# Generated by Django 4.0.3 on 2022-10-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOko', '0002_alter_adminuser_auth_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('url_slug', models.CharField(max_length=255, verbose_name='URL-имя')),
                ('thumbnail', models.FileField(blank=True, default='nofoto.jpeg', null=True, upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='created_ad',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='category_id',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppOko.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.CharField(max_length=255, verbose_name='URL-название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppOko.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_discount_price',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='is_active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppOko.chapters', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='products',
            name='chapters_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppOko.chapters'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppOko.chapters', verbose_name='Раздел'),
        ),
    ]
