# Generated by Django 4.0.3 on 2022-10-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOko', '0003_chapters_remove_categories_created_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='created_ad',
        ),
    ]
