# Generated by Django 4.0.3 on 2022-11-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOko', '0005_categorygallery_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategories_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppOko.subcategories'),
        ),
    ]
