# Generated by Django 4.1.4 on 2023-02-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0006_alter_products_subcategories_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(blank=True, max_length=150, null=True)),
                ("number", models.CharField(blank=True, max_length=150, null=True)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("client", models.CharField(blank=True, max_length=150, null=True)),
                ("manager", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customeruser",
            name="profile_pic",
            field=models.FileField(blank=True, default="", null=True, upload_to=""),
        ),
    ]
