<<<<<<< Updated upstream
# Generated by Django 4.0.3 on 2023-02-16 19:33
=======
# Generated by Django 4.1.4 on 2023-02-16 20:00
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< Updated upstream
        ('AppOko', '0007_projects_alter_customeruser_profile_pic'),
=======
        ("AppOko", "0007_projects_alter_customeruser_profile_pic"),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< Updated upstream
            name='projects',
            options={'ordering': ['-number']},
=======
            name="projects",
            options={"ordering": ["-number"]},
>>>>>>> Stashed changes
        ),
    ]
