# Generated by Django 4.1.4 on 2023-02-18 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0008_alter_projects_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    (1, "Admin"),
                    (2, "Staff"),
                    (3, "Customer"),
                    (4, "TempCustomer"),
                ],
                default=1,
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="TempCustomerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.FileField(blank=True, default="", null=True, upload_to=""),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auth_user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
