# Generated by Django 4.1.4 on 2023-02-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0011_chatroom_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": (("admin_permission", ""),)},
        ),
    ]
