# Generated by Django 4.1.4 on 2023-02-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0012_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminuser",
            options={"permissions": (("admin_permission", ""),)},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
