# Generated by Django 4.1.4 on 2023-02-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0013_alter_adminuser_options_alter_customuser_is_staff"),
    ]

    operations = []
