# Generated by Django 4.1.4 on 2023-02-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0014_auto_20230223_0319"),
    ]

    operations = []
