# Generated by Django 4.1.4 on 2023-03-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0018_alter_products_added_by_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="added_by_staff",
        ),
    ]
