# Generated by Django 4.1.4 on 2023-03-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppOko", "0023_remove_products_added_by_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="added_by_user",
        ),
    ]
