# Generated by Django 4.1.4 on 2023-03-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOko', '0025_products_added_by_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminchatmessage',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.CreateModel(
            name='AdminChatMessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_content', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOko.adminchatmessage')),
            ],
        ),
    ]
