# Generated by Django 4.1.7 on 2023-04-01 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOko', '0026_alter_adminchatmessage_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatReadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.IntegerField(default=0)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOko.adminchatmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOko.adminchatrooms')),
                ('user_for_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
